FROM alpine:latest


RUN apk update && \
    apk add --no-cache nginx php8-cli php8-pdo php8-pdo_mysql php8-json php8-mbstring && \
    mkdir -p /run/nginx


ADD https://github.com/vrana/adminer/releases/download/v4.8.0/adminer-4.8.0.php /usr/share/nginx/html/adminer.php


COPY nginx.conf /etc/nginx/nginx.conf


EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]
